### ISSUE TITLE
Start Page Component 작성

### ISSUE THREAD

**Issue by Seong1-Jo** [KDT-STFE-3-Team-2/Pig_the_Dice#4]
## 목적
Start Page Component를 작성하여 사용자가 메인 페이지로 이동할 수 있게 제공한다.

## Tasks

- [ ] input for name or id
- [ ] Move Main Component(submit)
- [ ] axios(name or id)
- [ ] Selector Player check(optional)
- [ ] Game rules(optional)
