### ISSUE TITLE
게임 시작 페이지 구현

### ISSUE THREAD

**Issue by Seong1-Jo** [KDT-STFE-3-Team-2/Pig_the_Dice#6]
## 목적
게임 시작 페이지 Component구현하여 사용자가 메인 페이지로 이동할 수 있게 제공한다.

## Tasks

- [ ] input for name or id
- [ ] Move Main Component(submit)
- [ ] Selector Player check(optional)
- [ ] Game rules(optional)

**Comment by ulgoon** [comment]
Perfect!
